APP_NAME: "My Platzky App"
SECRET_KEY: "$secret_key"

# Set to true once the site is served from a www domain.
USE_WWW: false

# How much detail goes into the logs: DEBUG, INFO, WARNING, ERROR or CRITICAL.
#LOG_LEVEL: INFO

LANGUAGES:
  en:
    name: English
    flag: uk
    country: GB

DB:
  TYPE: json_file
  PATH: "$data_filename"

# Uncomment feature flags if you want to change.
#FEATURE_FLAGS:
#  # Enable fake login for development. Never enable in production.
#  FAKE_LOGIN: false

#  # Remove HTML tags written in content only [html] renders html then
#  STRIP_CONTENT_HTML: false
