name: Testing pipeline

on:
  pull_request:
    branches:
      - main
      - next
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
  push:
    branches:
      - main
      - next
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Install Poetry
      run: pip install poetry==2.0.1
    - name: Set up Python 3.10
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.10"
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Run linters
      run: make lint-check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Install Poetry
      run: pip install poetry==2.0.1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Run tests with coverage
      run: make coverage
    - name: Add coverage to job summary
      if: matrix.python-version == '3.14'
      run: poetry run coverage report >> "$GITHUB_STEP_SUMMARY"

  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Install Poetry
      run: pip install poetry==2.0.1
    - name: Set up Python 3.14
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.14"
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Install Cypress
      working-directory: "./tests/e2e_tests"
      run: npm install cypress
    - name: Run e2e tests
      run: |
        make run-e2e-instance &
        sleep 3
        make e2e-tests
