name: Testing pipeline

on:
  pull_request:
    branches:
      - main
      - next
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'examples/**/*.json'
  push:
    branches:
      - main
      - next
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'examples/**/*.json'
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install Poetry
      run: pip install poetry==2.0.1 poetry-audit-plugin==1.0.0
    - name: Set up Python 3.10
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.10"
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Run linters
      run: make lint-check
    - name: Security audit
      run: make audit

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install Poetry
      run: pip install poetry==2.0.1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Run tests with coverage
      run: make coverage
    - name: Coveralls
      if: matrix.python-version == '3.10'
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
      with:
        path-to-lcov: "./coverage.lcov"
        github-token: ${{ secrets.GITHUB_TOKEN }}

  e2e:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install Poetry
      run: pip install poetry==2.0.1
    - name: Set up Python 3.14
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.14"
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Install Cypress
      working-directory: "./tests/e2e_tests"
      run: npm install cypress
    - name: Run e2e tests
      run: |
        make run-e2e-instance &
        sleep 3
        make e2e-tests
